---
- hosts: localhost
  gather_facts: false
  tasks:
   - name: Get CPU usage 
     shell: "top -b -n 1" 
     register: cpu_output

    - name: output of cpu usage
      debug:
        msg: "{{cpu_output}}"
    
      



